### ISSUE TITLE
Remove and rotate secret_key_base from repo when we care about sessions

### ISSUE THREAD

**Issue by dradford** [bugcrowd/double_red#5]
https://github.com/bugcrowd/double_red/blob/2939c733b2bcea53697e899f6322cd64f434dd92/config/config.exs#L15

**Comment by paulfri** [comment]
Not necessary -- that config is overridden by the prod-specific config which specifies to pull the `SECRET_KEY_BASE` from the system environment. (https://github.com/bugcrowd/double_red/blob/5fc42afb3045bc753e5a88d213aaaf9f971cf5f8/config/prod.exs#L8). That secret is fine for dev/test sessions.
